version: 0.1.{build}

configuration:
- Release
- Debug

platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  KP_GmailClient_PrivateKey:
    secure: hsj6Wh8Wdf9Fv6M8Jxq7UAviEqLWkgyACCpKxe9/nLk/cQqaSqlj1eHKa6We/angKkhStPKUrOSUfS+TjkTXVDnJHw6dqHo0ZqEAi59d734Zs6LX+afq0xYeuM2urj1NNvn8PRrQOpT6+lg/cxjWpxkdI977ViWb4z0/jFrXEgNbDqxm+IYp3nwrq7giNGsIYN4EEMuIEO6LTLS9QOlK4UZRF/cirG7uon0B83cG4g0/QEHhu4Hj4b6u/fLBwLiqhV9UKgMHe+jcyZqKH/E6E4oy0bTTpzyKWWHyljuzvyXdFVNHzfbNIkcWan6T5tc433/ScJ9WbC94ULaaB2M55WRuDYF3LyqToXxRpu30v82iB/CGQp443CoMwNiOWsXIMfHpUgjL8jAQqI3pUJS2MC1kYFqIBYzt0nO3HQJ3OYagWbk7dwSJ/nVVGyu+vhF/j3FCsj5E1uk1wvXuy3MjjBWhQmh4qk6fPvtkf6R/A4aixFsV4LoK4ezk0ppaNuZwoeHYYTcvsFR4pvWd1MntqleqGbL/s3WPhZNT8tXjnd57WRlrzlkrN9bJSvUfaS1zW1QCMogavVJ/G4zv9FdEtvY7J4MY6G2hcxw7GwyVD4L54BB6ygEVTarh+xiqlJxuKx0cM9PDzPiT8ip/1MN5dYF6t0wGQVXh+omnCffjnBj5EX5XA1pDotUTfuFIfgpAK3f+zJFx/VazMwZX489VZ2VIM7bsDxfgThaT8lwImDuqwPKh2VlTGFiRu1DwmBvuOqCW/Pf4kkFPu+2lZstRPDL4sgqfNWPH86fqg2sg/H220Ts8mfXOYiBfct2dHDBRj1g+iU4k+w+JpppwpTDX9iefy+l8eT1O+IC0FFz3sFgCkUwvWAmRtOJqWXmhPNWf0xeN3EwLu/Z3YFadxinG3xidNSvHmq24ymg1yFChNL/YAn4ylf6n+tplndKei6JWpreJa9t32THC6tP+mEOKUyOGytgaGMfoxPfYaLXfS/+xe9au83jNzI5WbvxxBFg7M7QAsalO9ICGKSPvfXSbKwMzliewM/TMzqz4EAmFLYEG+xEwHInuHXemXbLGVmK2KwK2HBo6DQeGCAs8RK6Y8d02Wv1yeyFkca/w1QIYBqbJV/e7FcHlzHPsOGYyxnA5Y8jXr2OIN3uBJ3CQvggrCVzIEe8P/6bczqkcVACj1OEbXsfQQ1eWZAe3oYFKRU3qtNmosQ0Ewjp4ibPzSsiphL560Dx9B7tTV/oL6Vf9dmnwEZNG7ObR+IUzRApc2WamgYc1mgeTlst+6WZu00ye/L1lRcKuhauT4wfFAb75YK/hGw/D7mfxhW1Gb7otahVgcAORouwgQGXevvpYHow8+6P5YuPtwRgVZtO+62dlGvjzbZgiudr3XI/UvFa9HkXukg2reHqLkzwSX97MynRYBf7Y5lB9iQLiNtch3FJAvP413hs/wkjntcSa80mh1x2HEhgbNanJ/0suYprAk0Kbg4E8AhcRWkfUjSdcfZ++wG8hyck/b9OmLs+4ak/n++e2sRJgzyCgp1WTNNuPh00yerIAzUN3ll7NsKEB7fdNT5N9prg7jPQbpaAx1Uo86Fw20+2aTtn8XAEPqA3yaVV7iRst0sdyvMqie77DLZgCUE3gRO048mZa5VEwfs2b87yNmUP/4z5Gcx89zwWHR83UyiJXmZDjpqzQ35/B0aMi5GMIa8lZtyzPjL52OebFmPlTSLcQ3U4Up5hoLm3YEWDI9CJ/124zTDCTrw2lPO1lrIeLYyyHaOibw8aNB5WSGrx9asKw7x8gleRRcbyGL03VQGvVI34lSNLS+1wcfu7ajRZmONgq5mev8+Uv6XusIX0ZXrTlM82Jgz+TAK4RpjBE8rP2aTh6m6aTlXbtYzO8Ba1CcoAceTW1s5emPJ6ajVw+qeiE37V3qjicr2CWLR7dLGwv6RtTS2FCrhUS3rZvhZk7HJ92tCeRJZx4eR+pHnQWgUB6XHADszCGePoXJgmfM+LTzmJyP6Ccnds/YQdhIPm/mdIK3Us9lqJ4RFJaAPKiG0oNpHydf+pWNKcxFf9Si4TB9ny4RCm36jSj3W6jbfy5XwpBRPqf1515cV7H0d4dyAul8yQasprlonftVIjPr5oLDX/Y+vsKuw7YVO8zMiQSBuDsGc7mGycDOTc2ASFvYQx7nq4+blhMiEduZE2hnkvW4fEgYypqpVvV1RxW65c0J+9fI9sGgEcrNLowhs8Z9M2rJKMRX7ohjYq/X2DGGnDatjETqrvVedbZ6mgoyWGhvL3ZYKEotVcvuU+GlJSRmUtjXnpHg/bp+e7O2XgvtqPbHXgfHby/vtrkzsalIOfANDNtLZyMKV1A6hhDhW8Hb/i8G3HyWDKfX83SQYjHpbRJgSZEB3PLdrkFitJ830s4sOlhtQlWzO8RpVLp4mJwMxlBddM8feFzD+/HESwXr7Jq33Rop3QB7/2TwYc41FX6VcRmeOC7ZnN/jfCgQXrhcsKXBm2CfKLCwgWQB/q874zOdudUH+QLIdjgokT4135bhkPavlPS5z231AY2+4j+69ktYS8BzcZy4uxRccn6IFIlwjQiBz0vqE6J30VAgcWoFH0D6fW5+AJMG3w7yYSCorFTC16mwuXMoPBJwB/3vhsUBe68EfnCXItngDaOC3AHF7r+Q9aDeoz40o4QeEy2bdFYvRaaKowz6L+qEhMwq5dOgt/5but9WffoDMr+CVMfvics68boAi1d9pYlFsQ1iBQdy0ZrqTwmmg4EQ4eo2z29aroT9680PXg64wmUttJvf+DOncPs7tT/J5vIZCkFTtrzl3EnFE2X6UjAta/MoUUjkdC2PZv75GVpYYeUXq3U+tm2lFiOEPD5ReLnkgNmjU9HbKsk+pRdyvg5lU1FlkE1XObSw3Rxy7KVhkw4eZvwldssC4q1Sc+7Crd+3sNztN6D0xOMiX8/j77txwYpBjdS1aGlAQ26QSRKVnckpGeE+bwWslWjxoJFoKMF3wjDo4yABegPEeJarPe/dzgBDdg+3+KLeM/xK3p9v8bOf9KqUV+naGvmzTtchjfM2hcxygQGFoeRfHJkpIUz8OyIhQ==
  KP_GmailClient_ClientEmail:
    secure: cNCxTFPHwW+vEpXB9EijRimBOqZ4zd2lWcKm05gmoLIH3rL8fQLurLMZvMPOustRPJB8jtq6u0PYAR1xkq5KowVVDmaYKFZmm/gzsdnS5qk=
  KP_GmailClient_EmailAddress:
    secure: XcKWCKghmWlD4tgz1tKnXXRg7YYH2cTsv3w/kMm/tYU=
  NugetApiKey:
    secure: L7Vp0jAqqqdmHdGulSr+S7Rc6GypRkYhns8GfUDRyBqvUSSUsGGVKy/9b3Er21JJ

before_build:
- nuget restore Src\KP.GmailClient.sln

build:
  parallel: true
  verbosity: normal

deploy_script:
- ps: Build\Build.ps1 -configMode $Env:CONFIGURATION -cloneDir $Env:APPVEYOR_BUILD_FOLDER -nugetApiKey $Env:NugetApiKey
