version: 2.0.0.{build}
image: Visual Studio 2017
configuration:
- Release

platform: Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

environment:
  KP_GmailClient_PrivateKey:
    secure: SVlIV8UwbwkXTt/eId4hxHXiT/5kTQf6SnFUBSuONzwmx0fNfHbdA3AWRAoC2fnM4mGw1jQVmKwuUCxv5F7r7dtZz6peyw5zQZ/d2dYmuXhMJZzAXfcRm40F5MHMjxQC6CmPCANs8Z8enxTkCmY/d8bOybh4ijYKJRK6AfSrihL9Lxp5NVZhp+PJTHQ31yfCsCxbdu/rRBsAmilY4+moXKcK0FunftQlvtQk+dwe4GU/qm/N3WjeznMtavOVEqbRvZY83SKbNWFIqwM+bvGXKJ0V8OcS1pYvCV5Yhe8dR0CFasoMsIUvczXqodZ+urGn7voKdlXtuntqMT+VCTdYV1A/mgLCDv5kTCimCBDYzvwo+TxZmNBqK/uDtCssjrxytL1KfetXDEUxvbZkRS1abdy2g08A9IJhCKCKfXZ2i2BAafQL0CkdaUvAhR8cUnVrk/flLV36mfgWuVy6DhD5nzPZAm0tkEwvo76TZKf6jbry5i/XIajbgD0gCAiPm7O7JBy6lquItO24yZyBuiIsPRwmn3ErPExwzb/FrQ7x5cP7W7Djf+MUA41rwWNkfmzr8HVP/mc8gb3CU8isoXlLZgsljpN8WPZyZZks7ixZjqGjOC4XklYBRXa7R5lCBXPla/i/HJWaB5Y2hNQYoo0g6NF+Edz5wopiKywRTxzYC5P/QjcibVpOk6WMN5gCtw8KAV4gCyspEpfd5iX1G9rZ0LYZJxsbpKqeHgBzdnQc0Ja0dC/XLRBYC9kg7c8aWycmdLLinn8QagULvpQoZKyhGpY5nV+Ktioal/TxYPaEDNCXKR9JJfcUuVfttwxI9JTCOGaEprZMMRJs4sZyCeEQCE6APxtjDTWHf8+00uXrGhOBiERSpVj5aIut/BSETQ4kDcg56K9HHha1AkC5G70vIN4Osk2yYhsNNn/mIoVi5CCjBvlp82U7W6zX1E11cmDneTNA7fOlx3B9A2WUuZGcHhUcDPCyKtVEx90WBaklCeww4up2L/iXpVxWY5VAkgkhOGUGG2nal+V5Z3di7Iq767xR5nrsjm1xl0uyALyuV7hTpI4hcS3Di9VvDQsJhodJo2Cixsxz4SpPKUjb7WAGYpXxLfVM5SjnCNf0Ena/yHB5UNtZ/XUhix0k+2wwUq643V6m2ePXPIq/jKodlEW1XJZbztwmFvn7UhKM97bLpQPacovf2+D2ife/DKztXq+5Q1BmZba2RHWGTbDr6FGeQ6HytT+uYsquUSY+5dRPLs2AnveMbWoCY35GXi/FajLfvF/5FEINRtFMeWgLX3Bmu2NTWj9aZFKy5JqZ4rys/xIci/OkU+gSQ3dBrGexaIifg/DVKZ+Flb6Id7Cu2brXpqCPcke9CsjhYO7QJSMu4nJFm9bjUOpLX4aha6a26+5H1JZ+XMY/vMiihViqDVTZ3h06pvqInzLlNGtG30F+VtR8dYj43ABsOsB5+gVv1DolX+EpeTBP5UUzxQ1l5ho4lFKof3+DdUzEFdbKE4e2vH+B7sZzcvQioE1BwVX6by+afwTUwBblBR/qdCqp5PJViEYhymqOwg+ovMbUS90u+juEH3Xx0cMqxjgyJ7xmLVQuAfUzAyJ+WiVLBsilrUuFYdRvpgVNifbNlvvT2xPOIkySkO2dPmyYrYo1cQJv/P7ZhiGtxY0Z8J1G7OrHo6L2FClpg76gDQ/eHQY4SalEF58Uv/4zPQDwrOr1Cp9hbwWu8C+Ba4mI3fujT6YnGMvR9P+TTfyuyhknD8egNi1cEPtymguFoSa2wF36F2yTyniJpn5KV8oRjrGFT6U2XhkhGb5QXbND/SzAVTw6XN+vFl5hwNOQXbsji4/ClZ6qmgoEkgKzXdS1spEC/gKINbVV2wisTq3KdTA18lAwSzWEAbxdlpIDzfbKwfJhZYra7AaRNjNeLNe5SrfwnV/kkZmgsONXEFhaKwkJe1jCBt4h67yAtpY1ab0EL+C3CKYiTFYcVLwGVZnODsAxNJE++VyiN2FFCYLTGPt2DZr5lsNwLSPVLfJ08DlfoJEFqKmDkAKKmoV7S5MIlobWWbXydwCKYTntmtzcOa47Uni3ngMUZxkpDWZXJlUKYm6fNc/XDQn4aX50/RyrojMc3qqoCHqEx33zm8IV0uP5uqX+BBKZdmnNq2+ceWKPPS26+q3YFlaBgcQkn87E/ZrMhYWaVnhjIggZ/Eq7qKYvJYx2W0ZxBDB9MVNTzJepQ0rVBQIdzZiLFRp/IKee09HomdsGITeV+nySbQF7eMfwBkOsQpDVFHcIhCI51a6UM83ABksFlbK4MZFMyQDcoDxDHSwvLIhufeEu3wuFAIhQda3CY4A7XdqVdAOC9QDZsiiGKG3XDB+AjYwtgSuecBBLENv3dVprPZPwE2f5hhTP63hDpNqufJJgSP9VAqR/VOpe9WpOaDfA4JJOXygINLlMIaRoQ2MrKyfq7K+tHsW1iF7A81Xoiey22Ehw0a9ILU07yUmKtBo956fNALD9X3J/qQgBMjkJbbrOuk6gm6p14zjHYzRwH//Oagp/81pnAYExP+kpf/xCKDtcT4AlLaSQp9Pj1jdLU0LX2DXpDT8zZfGlEkkXSId614hf4a9KQOfpT5OCZrv904C+WREdU3uv7qOcHBveIiw3IQF+qKuZzX0KLJqM8rE3r2+p64mi1A4jA/0c9WHHfqQEnOCy9YYuj2Z+vuBPDq60wWxXY7IzLPyGV4TFWOUK5F+oaoCnYd+arcOPYQAHnXzBJqn4uBvgMPOYGVvRcUdhiTHIJPjXrC1bIxgSboycZ4f9n63Dj7sj1qROYt59z71a+Dj4jgN5HBBOErrKs/yZT2n9Ew8K189wc1DIdSo5k+mki+8mqATn2XoiAv3liiIPaJHOGmAhyv8akW8D1ErndZSu3SYPDsb5JiKSm5SXmhgkesfgevT4pDv+n+fpj8gbz0LLl2+vFj1pGq6XdaFSK4hRzxhkGp1IFrY3TYi8A/84xrZefQ8/P7GwBhxnQ2ngccNP9w/HKR1j6Zqne8s487BOOMdmoFlcWxDgw6kHuzyW/YsJkNfI+nC/zIvZl7EU5ivxzxhgLXk61i2/zg==
  KP_GmailClient_ClientEmail:
    secure: cNCxTFPHwW+vEpXB9EijRimBOqZ4zd2lWcKm05gmoLIH3rL8fQLurLMZvMPOustRPJB8jtq6u0PYAR1xkq5KowVVDmaYKFZmm/gzsdnS5qk=
  KP_GmailClient_EmailAddress:
    secure: XcKWCKghmWlD4tgz1tKnXXRg7YYH2cTsv3w/kMm/tYU=

before_build:
- cmd: dotnet --version
- cmd: dotnet pack

nuget:
  disable_publish_on_pr: true

build:
  parallel: true
  verbosity: normal

artifacts:
- path: '**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: 0+KasU/ReqcTKVPDfXpA5lLegWh5dmXAYizx6aiWVDOTFzU29Dljc7AlfMiSekMf
  on:
    APPVEYOR_REPO_TAG: true
